// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package utils

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEc280810DecodeGithubComStudtoolAuthServiceUtils(in *jlexer.Lexer, out *JwtClaims) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "UserId":
			out.UserId = string(in.String())
		case "ExpTime":
			out.ExpTime = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEc280810EncodeGithubComStudtoolAuthServiceUtils(out *jwriter.Writer, in JwtClaims) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"UserId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.UserId))
	}
	{
		const prefix string = ",\"ExpTime\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ExpTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v JwtClaims) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEc280810EncodeGithubComStudtoolAuthServiceUtils(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v JwtClaims) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEc280810EncodeGithubComStudtoolAuthServiceUtils(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *JwtClaims) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEc280810DecodeGithubComStudtoolAuthServiceUtils(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *JwtClaims) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEc280810DecodeGithubComStudtoolAuthServiceUtils(l, v)
}
